"use client"
import React from 'react'
import TopNav from '@/components/TopNav'
import { Award, FileText, Download, Share2, ShieldCheck, Languages, Zap } from 'lucide-react'

export default function CertificationCenter() {
  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 pb-20">
      <TopNav />
      
      <main className="max-w-6xl mx-auto py-12 px-8">
        <div className="text-center mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 bg-green-50 text-green-600 px-6 py-2 rounded-full border border-green-100">
            <ShieldCheck size={16} />
            <span className="text-[10px] font-black uppercase tracking-widest">Summative Exam Verified</span>
          </div>
          <h1 className="text-5xl font-black uppercase italic tracking-tighter">Competency Achieved.</h1>
          <p className="text-slate-500 font-medium">Your technical credentials have been generated by the Cobel AI Engine.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
          
          {/* SECTION 1: THE CERTIFICATE PREVIEW */}
          <div className="space-y-6">
            <h3 className="text-xs font-black uppercase tracking-[0.3em] text-slate-400">Official Certificate</h3>
            <div className="aspect-[1.414/1] bg-white border-[12px] border-slate-900 p-12 flex flex-col justify-between relative shadow-2xl overflow-hidden">
              <div className="absolute top-0 right-0 p-8 opacity-5">
                <Award size={200} />
              </div>
              
              <div className="flex justify-between items-start relative z-10">
                <div className="font-black text-xl italic uppercase">COBEL <span className="text-blue-600">LMS</span></div>
                <div className="text-[8px] font-bold uppercase tracking-widest text-right">ID: CB-2026-9942<br/>Issued: Feb 06, 2026</div>
              </div>

              <div className="text-center space-y-4 relative z-10">
                <p className="text-[10px] font-black uppercase tracking-[0.5em] text-blue-600">Certificate of Technical Fluency</p>
                <h2 className="text-4xl font-black uppercase italic text-slate-900 tracking-tighter">Abel C. Student</h2>
                <div className="w-24 h-1 bg-slate-200 mx-auto"></div>
                <p className="text-[11px] font-medium text-slate-600 max-w-xs mx-auto">
                  Has successfully demonstrated professional mastery in 
                  <span className="font-black text-slate-900"> INDUSTRIAL HYDRAULIC SYSTEMS</span> 
                  via the Cobel AI Optimized Path.
                </p>
              </div>

              <div className="flex justify-between items-end relative z-10">
                <div className="text-left">
                  <div className="h-px w-32 bg-slate-300 mb-2"></div>
                  <p className="text-[8px] font-black uppercase">Technical Director</p>
                </div>
                <div className="w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center text-white">
                  <ShieldCheck size={32} />
                </div>
              </div>
            </div>
            <button className="w-full bg-slate-900 text-white py-5 rounded-2xl font-black uppercase text-xs flex items-center justify-center gap-3 hover:bg-blue-600 transition-all">
              <Download size={16} /> Download High-Res PDF
            </button>
          </div>

          {/* SECTION 2: THE TRANSCRIPT */}
          <div className="space-y-6">
            <h3 className="text-xs font-black uppercase tracking-[0.3em] text-slate-400">Technical Transcript</h3>
            <div className="bg-white rounded-[3rem] p-10 border border-slate-100 shadow-xl space-y-8">
              
              <div className="flex justify-between border-b border-slate-50 pb-6">
                <div>
                  <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Temporal Optimization</p>
                  <div className="flex items-center gap-2 mt-1">
                    <Zap size={16} className="text-blue-600" />
                    <span className="text-xl font-black italic">14.5 HRS SAVED</span>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Bilingual Fluency</p>
                  <div className="flex items-center gap-2 mt-1 justify-end">
                    <Languages size={16} className="text-blue-600" />
                    <span className="text-xl font-black italic">B2 ADVANCED</span>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <TranscriptRow label="Module 01: Baseline Safety" score="98%" />
                <TranscriptRow label="Module 04: Hydraulic Ingestion" score="94%" />
                <TranscriptRow label="Module 08: Summative Assessment" score="96%" />
                <TranscriptRow label="Handwriting Extraction Accuracy" score="99%" />
                <TranscriptRow label="Audio Fluency (EN/FR)" score="B2+" />
              </div>

              <div className="bg-slate-50 p-6 rounded-3xl">
                <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-2">Trainer's Final Validation</p>
                <p className="text-[11px] font-medium italic text-slate-600">
                  "Candidate demonstrates exceptional ability in translating technical logic from physical blueprints to bilingual verbal reporting."
                </p>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <button className="bg-white border border-slate-200 py-5 rounded-2xl font-black uppercase text-[10px] tracking-widest flex items-center justify-center gap-2 hover:bg-slate-50 transition-all">
                <Share2 size={14} /> Share to LinkedIn
              </button>
              <button className="bg-white border border-slate-200 py-5 rounded-2xl font-black uppercase text-[10px] tracking-widest flex items-center justify-center gap-2 hover:bg-slate-50 transition-all">
                <FileText size={14} /> Export CSV Data
              </button>
            </div>
          </div>

        </div>
      </main>
    </div>
  )
}

function TranscriptRow({ label, score }: any) {
  return (
    <div className="flex justify-between items-center py-2 border-b border-slate-50 last:border-0">
      <span className="text-[10px] font-bold text-slate-500 uppercase">{label}</span>
      <span className="text-[11px] font-black text-slate-900 uppercase italic">{score}</span>
    </div>
  )
}